user:
    path:  /
    defaults: { _controller: "UserBundle:User:index" }

user_show:
    path:  /{id}/show/
    defaults: { _controller: "UserBundle:User:show" }

user_new:
    path:  /new/
    defaults: { _controller: "UserBundle:User:new" }

user_create:
    path:  /create/
    defaults: { _controller: "UserBundle:User:create" }
    requirements: { methods: post }

user_edit:
    path:  /{id}/edit/
    defaults: { _controller: "UserBundle:User:edit" }

user_update:
    path:  /{id}/update/
    defaults: { _controller: "UserBundle:User:update" }
    requirements: { methods: post|put }

user_delete:
    path:  /{id}/delete/
    defaults: { _controller: "UserBundle:User:delete" }
    requirements: { methods: post|delete|get }