imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@LayerBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   '%database_driver%'
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.root_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'
#        types:
#            geography:
#                class: 'Jsor\Doctrine\PostGIS\Types\GeographyType'
#                commented: false
#            geometry:
#                class: 'Jsor\Doctrine\PostGIS\Types\GeometryType'
#                commented: false
#            raster:
#                class: 'Jsor\Doctrine\PostGIS\Types\RasterType'
#                commented: false

        types:
            geography: 'Jsor\Doctrine\PostGIS\Types\GeographyType'
            geometry: 'Jsor\Doctrine\PostGIS\Types\GeometryType'
            raster: 'Jsor\Doctrine\PostGIS\Types\RasterType'
    orm:
        dql:
            string_functions:
                ST_Area:  Jsor\Doctrine\PostGIS\Functions\ST_Area
                ST_AsGeoJSON:  Jsor\Doctrine\PostGIS\Functions\ST_AsGeoJSON
                Geometry: Jsor\Doctrine\PostGIS\Functions\Geometry
                ST_Distance: Jsor\Doctrine\PostGIS\Functions\ST_Distance
                ST_Distance_Sphere: Jsor\Doctrine\PostGIS\Functions\ST_Distance_Sphere
                ST_DWithin: Jsor\Doctrine\PostGIS\Functions\ST_DWithin
                ST_GeomFromText: Jsor\Doctrine\PostGIS\Functions\ST_GeomFromText
                ST_GeographyFromText: Jsor\Doctrine\PostGIS\Functions\ST_GeographyFromText
                ST_Transform: Jsor\Doctrine\PostGIS\Functions\ST_Transform
                ST_Point: Jsor\Doctrine\PostGIS\Functions\ST_Point
                ST_SetSRID: Jsor\Doctrine\PostGIS\Functions\ST_SetSRID
                ST_AsEWKT: Jsor\Doctrine\PostGIS\Functions\ST_AsEWKT

        auto_generate_proxy_classes: '%kernel.debug%'
#        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true


# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
