# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    jsor:    
        class: Jsor\Doctrine\PostGIS\Event\ORMSchemaEventSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
