<?php

namespace LayerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SueloAfectadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccionSueloRepository extends EntityRepository {

    /**
     * Consulta DQL para encontrar las acciones correspondientes a una parcela de suelo
     *
     * SQL equivalente:
     *
     * <b>select accion.id, accion.nombre, asociacion.hecho
     * from accion_suelo as asociacion
     * inner join accion_de_mejoramiento as accion on (asociacion.accion_id = accion.id)
     * where suelo_id=<$suelo>
     * order by accion.nombre</b>
     *
     * @param type $suelo
     * @return type
     */
    public function buscarAcciones($suelo) {
        $qb = $this->createQueryBuilder('asociacion');
        $qb->select('accion.id, accion.nombre, asociacion.hecho')
                ->innerJoin('asociacion.accion', 'accion')
                ->where($qb->expr()->eq(':suelo', 'asociacion.suelo'))
                ->orderBy('accion.nombre')
                ->setParameter('suelo', $suelo)
        ;

        return $qb;
    }

    /**
     * Consulta DQL para actualizar el estado de las acciones correspondientes a una parcela de suelo
     *
     * @param type $suelo
     * @param type $acciones
     * @return type
     */
    public function actualizarAcciones($suelo, $acciones) {
        $qb = $this->createQueryBuilder('asociacion');
//        $qb->update()->set('hecho', $acciones['hecho']);
//        foreach ($acciones as $id => $hecho) {
//            $qb->orWhere($qb->expr()->eq(':accion' . $id, 'accion.id'))
//                    ->setParameter('accion' . $id, $a);
//        }
//        $qb->andWhere($qb->expr()->eq(':suelo', 'suelo.gid'))
//                ->setParameter('suelo', $suelo);

        return $qb;
    }

}
