<?php

namespace LayerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ParcelaAgricolaAfectadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccionDeMejoramientoRepository extends EntityRepository {

    /**
     * Consulta DQL para la obtención de la lista de acciones no asociadas a la parcela de suelo $suelo_id
     *
     * SQL equivalente:
     *
     * select * from accion_de_mejoramiento
     * where id not in
     * (SELECT a0_.id AS id0 FROM accion_de_mejoramiento a0_
     * INNER JOIN accion_suelo a1_ ON (a0_.id = a1_.accion_id) WHERE a1_.suelo_id = 111)
     * order by nombre
     *
     * @param type $suelo_id
     * @return type
     */
    public function accionesDisponibles($suelo_id) {
        $sqb = $this->createQueryBuilder('accion_aux');

        $sqb->select('accion_aux.id')->distinct()
                ->innerJoin('LayerBundle:AccionSuelo', 'asociacion', \Doctrine\ORM\Query\Expr\Join::WITH, 'accion_aux.id = asociacion.accion')
                ->where($sqb->expr()->eq('asociacion.suelo', ':suelo'))
                ->setParameter('suelo', $suelo_id)
        ;

        $qb = $this->createQueryBuilder('accion')->select('accion.id, accion.nombre');
        $qb->where($qb->expr()->notIn('accion.id', $sqb->getQuery()->getDQL()))
                ->setParameter('suelo', $suelo_id)
        ;

        return $qb;
    }

}
