<?php

namespace LayerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AscensoNMMRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AscensoNMMRepository extends EntityRepository {

    /**
     * Consulta DQL para obtener los años (diferentes) actualmente comprendidos en la tabla ascenso_nmm
     *
     * @return type
     */
    public function findAnnos() {
        $qb = $this->createQueryBuilder('ascenso');
        $qb->select('ascenso.yearAscenso as anno')->distinct();

        return $qb;
    }

}
