<?php

namespace LayerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ParcelaAgricolaAfectadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParcelaAgricolaAfectadaRepository extends EntityRepository {

    /**
     * Crea la consulta DQL para obtener
     * <b>parcela.formaProd, poseedor.municipio, poseedor.nombre y sum(parcela.area)</b>
     * donde <b>poseedor</b> corresponda a una CCS, UBPC o CPA.
     *
     * SQL equivalente:
     *
     * select forma_prod, poseedor.municipio, poseedor.nombre, sum(area) from parcela_agricola_afectada
     * inner join poseedor on (parcela_agricola_afectada.forma_prod = poseedor.identidad)
     * where
     * forma_prod like '72552%' or
     * forma_prod like '72595%' or
     * forma_prod like '72563%'
     * group by poseedor.municipio, forma_prod, poseedor.nombre
     * order by parcela_agricola_afectada.forma_prod
     *
     * @param type $codigos
     * @return type
     */
    public function findByFormaProductiva($codigos) {

        $qb = $this->createQueryBuilder('parcela');
        $qb->select('parcela.formaProd as idFormaProd, poseedor.municipio, poseedor.nombre, sum(parcela.area)  as area')
                ->innerJoin('LayerBundle:Poseedor', 'poseedor', \Doctrine\ORM\Query\Expr\Join::WITH, 'parcela.formaProd = poseedor.identidad');

        foreach ($codigos as $k => $c) {
            $qb->orWhere($qb->expr()->like('parcela.formaProd', ':codigo' . $k))
                    ->setParameter('codigo' . $k, $k . '%');
        }

        $qb->groupBy('poseedor.municipio, parcela.formaProd, poseedor.nombre')
                ->orderBy('poseedor.municipio, parcela.formaProd');
        return $qb;
    }

    public function findByUsufructo() {
//        select municipio_nombre, count(*), sum(area) as area from parcela_agricola_afectada where usufructo='SI' group by municipio_nombre
        $qb = $this->createQueryBuilder('parcela');
        $qb->select('parcela.municipioNombre, count(parcela.usufructo) as usufructos, sum(parcela.area) as area')
                ->where($qb->expr()->eq('parcela.usufructo', $qb->expr()->literal('SI')))
                ->groupBy('parcela.municipioNombre');

        return $qb;
    }

}
