<?php

namespace LayerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PoseedorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoseedorRepository extends EntityRepository {
    /**
     *
     * @param type $codigos
     * @return type
     */
//    public function findByParticularAsociado($codigos) {
////select asociado, municipio_nombre, aux_select.nombre, sum(area) from poseedor
////inner join (select identidad, nombre from poseedor) as aux_select on (aux_select.identidad = cast(asociado as varchar))
////inner join parcela_agricola_afectada on (poseedor.identidad = poseedor)
////where
////cast(asociado as varchar) like '72552%' or
////cast(asociado as varchar) like '72595%' or
////cast(asociado as varchar) like '72563%'
////group by asociado, municipio_nombre, aux_select.nombre
////order by asociado
//
//        $qb = $this->createQueryBuilder('p');
//        $qb->select('p.asociado, pa.municipioNombre, sum(pa.area) as area')
//                ->innerJoin('LayerBundle:ParcelaAgricolaAfectada', 'aux_select');
//
//        foreach ($codigos as $k => $c) {
//            $qb->orWhere($qb->expr()->like('p.poseedor', ':codigo' . $k))
//                    ->setParameter('codigo' . $k, $k . '%');
//        }
//
//        $qb->groupBy('p.municipioNombre, p.poseedor')
//                ->orderBy('p.municipioNombre, p.poseedor');
//
//        return $qb;
//    }
}
