<?php

namespace LayerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SueloAfectadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SueloAfectadoRepository extends EntityRepository {

    /**
     * Consulta DQL para obtener los suelos afectados por sus IDs
     *
     * @return QueryBuilder
     */
    public function findByIDs($suelosIntersectados) {
        $qb = $this->createQueryBuilder('suelo');
//        $qb->select('accion.nombre, asociacion.hecho')->distinct();
        $qb->select('accion.nombre')->distinct();
        $qb->innerJoin('suelo.asociacionAccionSuelo', 'asociacion');
        $qb->innerJoin('asociacion.accion', 'accion');
        foreach ($suelosIntersectados as $s) {
            $qb->orWhere($qb->expr()->eq(':gid' . $s, 'suelo.gid'))
                    ->setParameter('gid' . $s, $s);
        }

        return $qb;
    }

}
