layer_homepage:
    path:     /
    defaults: { _controller: LayerBundle:Default:index }

layer_sueloafectado:
    resource: "@LayerBundle/Resources/config/routing/sueloafectado.yml"
    prefix: /suelo_afectado/

layer_parcelaagricolaafectada:
    resource: "@LayerBundle/Resources/config/routing/parcelaagricolaafectada.yml"
    prefix: /parcela_agricola_afectada/

layer_ascensonmm:
    resource: "@LayerBundle/Resources/config/routing/ascensonmm.yml"
    prefix:   /ascenso_nmm/

layer_acciondemejoramiento:
    resource: "@LayerBundle/Resources/config/routing/acciondemejoramiento.yml"
    prefix:   /acciondemejoramiento/